bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import registerPage,login,logoutUser
from admistration.views import eventview
import notifications.urls
admin.site.site_header="Admin Login"
admin.site.site_title="Admin | Dashboard"
admin.site.index_title="Welcome to admin panel"
urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', login, name='login'),
    path('register/',registerPage,name='register'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('product/', include('products.urls', namespace='product')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('login/',login,name='login'),
    path('logout/',logoutUser,name='logout'),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('admistration/',include('admistration.urls')),
    path('event/', eventview, name='eventview'),



]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

products/urls.py
from django.urls import path, re_path
from .views import *
app_name = 'product'

urlpatterns = [

    path('', ProductListView, name='productlist'),
    path('<pk>/',ProductProfileDetailView.as_view(),name='details'),
    path('s/ad/',AdvertiseListView,name='eventlist'),

    ]

products/models.py
from django.db import models

from django.db import models
from PIL import Image


# Create your models here.
class category(models.Model):
    name = models.CharField(max_length=50, default="")

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    product_id = models.CharField(max_length=50, primary_key=True, blank=False)
    product_name = models.CharField(max_length=200, blank=False)
    product_description = models.TextField(max_length=300, blank=True)
    category = models.ForeignKey(category, default="", verbose_name="Category", on_delete=models.SET_DEFAULT, null=True)
    image1 = models.ImageField(upload_to='products/images', default="", null=True)
    image2 = models.ImageField(upload_to='products/images', default="", null=True, blank=True)
    image3 = models.ImageField(upload_to='products/images', default="", null=True, blank=True)
    price = models.FloatField(default=0.0, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img1 = Image.open(self.image1.path)
        if img1.height > 1500 or img1.width > 1500:
            output_size = (1500, 1500)
            img1.thumbnail(output_size)
            img1.save(self.image1.path)
        if self.image2:
            img2 = Image.open(self.image2.path)
            if img2.height > 1500 or img2.width > 1500:
                output_size = (1500, 1500)
                img2.thumbnail(output_size)
                img2.save(self.image2.path)

        if self.image3:
            img3 = Image.open(self.image3.path)
            if img3.height > 1500 or img3.width > 1500:
                output_size = (1500, 1500)
                img3.thumbnail(output_size)
                img3.save(self.image3.path)

    def __str__(self):
        return f'{self.product_id}--{self.product_name}'

    def all_profuct_list(self):
        product = Product.objects.all()
        return product


class Advertisement(models.Model):
    name = models.CharField(max_length=50, blank=False)
    product = models.ManyToManyField(Product, verbose_name="Product", related_name='products')
    image= models.ImageField(upload_to='advertise', default="", null=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __str__(self):
        return f'{self.name}'

products/forms.py
from django import forms
class MyForm(forms.Form):
    date = forms.DateField( validators=[present_or_future_date])

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from .models import *
from django.views.generic import DetailView

@login_required
def ProductListView(request):
    qs = Product.objects.all()

    context = {'qs': qs}

    return render(request, 'product/productlist.html', context)

class ProductProfileDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = ('product/details.html')

    def get_context_data(self, **kwargs):
        product_id=self.kwargs.get('pk')
        obj=Product.objects.get(product_id=product_id)
        context = {'qs': obj}
        return context

#@login_required
def AdvertiseListView(request):
    qs = Advertisement.objects.all()

    context = {'qs': qs}

    return render(request, 'product/eventlist.html', context)

products/templates/product/details.html
{% extends 'base.html' %}
{% load static %}
{% block main_head %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
<style>


.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 15px;
  display: flex;
}

/* Columns */
.left-column {
  width: 65%;
  position: relative;
}

.right-column {
  width: 35%;
  margin-top: 60px;
}


/* Left Column */
.left-column img {
  width: 100%;
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
  transition: all 0.3s ease;
}

.left-column img.active {
  opacity: 1;
}


/* Right Column */

/* Product Description */
.product-description {
  border-bottom: 1px solid #E1E8EE;
  margin-bottom: 20px;
}
.product-description span {
  font-size: 12px;
  color: #358ED7;
  letter-spacing: 1px;
  text-transform: uppercase;
  text-decoration: none;
}
.product-description h1 {
  font-weight: 300;
  font-size: 52px;
  color: #43484D;
  letter-spacing: -2px;
}
.product-description p {
  font-size: 16px;
  font-weight: 300;
  color: #86939E;
  line-height: 24px;
}

/* Product Configuration */
.product-color span,
.cable-config span {
  font-size: 14px;
  font-weight: 400;
  color: #86939E;
  margin-bottom: 20px;
  display: inline-block;
}

/* Product Color */
.product-color {
  margin-bottom: 30px;
}

.color-choose div {
  display: inline-block;
}

.color-choose input[type="radio"] {
  display: none;
}

.color-choose input[type="radio"] + label span {
  display: inline-block;
  width: 40px;
  height: 40px;
  margin: -1px 4px 0 0;
  vertical-align: middle;
  cursor: pointer;
  border-radius: 50%;
}

.color-choose input[type="radio"] + label span {
  border: 2px solid #FFFFFF;
  box-shadow: 0 1px 3px 0 rgba(0,0,0,0.33);
}

.color-choose input[type="radio"]#red + label span {
  background-color: #C91524;
}
.color-choose input[type="radio"]#blue + label span {
  background-color: #314780;
}
.color-choose input[type="radio"]#black + label span {
  background-color: #323232;
}

.color-choose input[type="radio"]:checked + label span {
  background-image: url(images/check-icn.svg);
  background-repeat: no-repeat;
  background-position: center;
}

/* Cable Configuration */
.cable-choose {
  margin-bottom: 20px;
}

.cable-choose button {
  border: 2px solid #E1E8EE;
  border-radius: 6px;
  padding: 13px 20px;
  font-size: 14px;
  color: #5E6977;
  background-color: #fff;
  cursor: pointer;
  transition: all .5s;
}

.cable-choose button:hover,
.cable-choose button:active,
.cable-choose button:focus {
  border: 2px solid #86939E;
  outline: none;
}

.cable-config {
  border-bottom: 1px solid #E1E8EE;
  margin-bottom: 20px;
}

.cable-config a {
  color: #358ED7;
  text-decoration: none;
  font-size: 12px;
  position: relative;
  margin: 10px 0;
  display: inline-block;
}
.cable-config a:before {
  content: "?";
  height: 15px;
  width: 15px;
  border-radius: 50%;
  border: 2px solid rgba(53, 142, 215, 0.5);
  display: inline-block;
  text-align: center;
  line-height: 16px;
  opacity: 0.5;
  margin-right: 5px;
}

/* Product Price */
.product-price {
  display: flex;
  align-items: center;
}

.product-price span {
  font-size: 26px;
  font-weight: 300;
  color: #43474D;
  margin-right: 20px;
}

.cart-btn {
  display: inline-block;
  background-color: #7DC855;
  border-radius: 6px;
  font-size: 16px;
  color: #FFFFFF;
  text-decoration: none;
  padding: 12px 30px;
  transition: all .5s;
}
.cart-btn:hover {
  background-color: #64af3d;
}

/* Responsive */
@media (max-width: 940px) {
  .container {
    flex-direction: column;
    margin-top: 60px;
  }

  .left-column,
  .right-column {
    width: 100%;
  }

  .left-column img {
    width: 300px;
    right: 0;
    top: -65px;
    left: initial;
  }
}

@media (max-width: 535px) {
  .left-column img {
    width: 220px;
    top: -85px;
  }
}

</style>
{% endblock main_head %}

{% block content %}

 <main class="container">


      <div class="left-column">
<!--        <img data-image="black" src="{{qs.image1.url}}" alt="">-->
<!--        <img data-image="blue" src="#" alt="">-->
        <img width="100px" height="80%" data-image="red" class="active" src="{{qs.image1.url}}" alt="">
      </div>


      <!-- Right Column -->
      <div class="right-column">

        <!-- Product Description -->
        <div class="product-description">

          <h1>{{qs.product_name}}</h1>
            <p>{{qs.product_description}}</p></div>

        <!-- Product Configuration -->
        <div class="product-configuration">

          <!-- Product Color -->
<!--          <div class="product-color">-->
<!--            <span>Color</span>-->

<!--            <div class="color-choose">-->
<!--              <div>-->
<!--                <input data-image="red" type="radio" id="red" name="color" value="red" checked>-->
<!--                <label for="red"><span></span></label>-->
<!--              </div>-->
<!--              <div>-->
<!--                <input data-image="blue" type="radio" id="blue" name="color" value="blue">-->
<!--                <label for="blue"><span></span></label>-->
<!--              </div>-->
<!--              <div>-->
<!--                <input data-image="black" type="radio" id="black" name="color" value="black">-->
<!--                <label for="black"><span></span></label>-->
<!--              </div>-->
<!--            </div>-->

<!--          </div>-->

          <!-- Cable Configuration -->
          <div class="cable-config">
            <span>Cable configuration</span>

            <div class="cable-choose">
              <button>{{qs.category}}</button>

            </div>


          </div>
        </div>

        <!-- Product Pricing -->
        <div class="product-price">
          <span>{{qs.price}}$</span>
          <a href="#" class="cart-btn">Order Now</a>
        </div>
      </div>
    </main>


{% endblock content %}
{% block scripts %}

{% endblock scripts %}

products/templates/product/eventlist.html
{{ad.image.url}}

products/templates/product/productlist.html
{% extends 'base.html' %}
{% load static %}
{% block main_head %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
<style>
	.spacer {
    height: 50px;
}
.slides {
    padding: 0;
    width: 609px;
    height: 420px;
    display: block;
    margin: 0 auto;
    position: relative;
}

.slides * {
    user-select: none;
    -ms-user-select: none;
    -moz-user-select: none;
    -khtml-user-select: none;
    -webkit-user-select: none;
    -webkit-touch-callout: none;
}

.slides input { display: none; }

.slide-container { display: block; }

.slide {
    top: 0;
    opacity: 0;
    width: 609px;
    height: 420px;
    display: block;
    position: absolute;

    transform: scale(0);

    transition: all .7s ease-in-out;
}

.slide img {
    width: 100%;
    height: 100%;
}

.nav label {
    width: 200px;
    height: 100%;
    display: none;
    position: absolute;

	  opacity: 0;
    z-index: 9;
    cursor: pointer;

    transition: opacity .2s;

    color: #FFF;
    font-size: 156pt;
    text-align: center;
    line-height: 380px;
    font-family: "Varela Round", sans-serif;
    background-color: rgba(255, 255, 255, .3);
    text-shadow: 0px 0px 15px rgb(119, 119, 119);
}

.slide:hover + .nav label { opacity: 0.5; }

.nav label:hover { opacity: 1; }

.nav .next { right: 0; }

input:checked + .slide-container  .slide {
    opacity: 1;

    transform: scale(1);

    transition: opacity 1s ease-in-out;
}

input:checked + .slide-container .nav label { display: block; }

.nav-dots {
	width: 100%;
	bottom: 9px;
	height: 11px;
	display: block;
	position: absolute;
	text-align: center;
}

.nav-dots .nav-dot {
	top: -5px;
	width: 11px;
	height: 11px;
	margin: 0 4px;
	position: relative;
	border-radius: 100%;
	display: inline-block;
	background-color: rgba(0, 0, 0, 0.6);
}

.nav-dots .nav-dot:hover {
	cursor: pointer;
	background-color: rgba(0, 0, 0, 0.8);
}

input#img-1:checked ~ .nav-dots label#img-dot-1,
input#img-2:checked ~ .nav-dots label#img-dot-2,
input#img-3:checked ~ .nav-dots label#img-dot-3,
input#img-4:checked ~ .nav-dots label#img-dot-4,
input#img-5:checked ~ .nav-dots label#img-dot-5,
input#img-6:checked ~ .nav-dots label#img-dot-6 {
	background: rgba(0, 0, 0, 0.8);
}
</style>

<script type="text/javascript">
        window.jssor_1_slider_init = function() {

            var jssor_1_SlideshowTransitions = [
              {$Duration:800,x:-0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:800,x:0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2}
            ];

            var jssor_1_options = {
              $AutoPlay: 1,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $Transitions: jssor_1_SlideshowTransitions,
                $TransitionsOrder: 1
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $ThumbnailNavigatorOptions: {
                $Class: $JssorThumbnailNavigator$,
                $Orientation: 2,
                $NoDrag: true
              }
            };

            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

            /*#region responsive code begin*/

            var MAX_WIDTH = 980;

            function ScaleSlider() {
                var containerElement = jssor_1_slider.$Elmt.parentNode;
                var containerWidth = containerElement.clientWidth;

                if (containerWidth) {

                    var expectedWidth = Math.min(MAX_WIDTH || containerWidth, containerWidth);

                    jssor_1_slider.$ScaleWidth(expectedWidth);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }

            ScaleSlider();

            $Jssor$.$AddEvent(window, "load", ScaleSlider);
            $Jssor$.$AddEvent(window, "resize", ScaleSlider);
            $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
            /*#endregion responsive code end*/
        };
    </script>
 <style>
        /*jssor slider loading skin spin css*/
        .jssorl-009-spin img {
            animation-name: jssorl-009-spin;
            animation-duration: 1.6s;
            animation-iteration-count: infinite;
            animation-timing-function: linear;
        }

        @keyframes jssorl-009-spin {
            from { transform: rotate(0deg); }
            to { transform: rotate(360deg); }
        }

        .jssora061 {display:block;position:absolute;cursor:pointer;}
        .jssora061 .a {fill:none;stroke:#fff;stroke-width:360;stroke-linecap:round;}
        .jssora061:hover {opacity:.8;}
        .jssora061.jssora061dn {opacity:.5;}
        .jssora061.jssora061ds {opacity:.3;pointer-events:none;}
    </style>
{% endblock main_head %}

{% block content %}

<div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:980px;height:380px;overflow:hidden;visibility:hidden;">
        <!-- Loading Screen -->
        <div data-u="loading" class="jssorl-009-spin" style="position:absolute;top:0px;left:0px;width:100%;height:100%;text-align:center;background-color:rgba(0,0,0,0.7);">
            <img style="margin-top:-19px;position:relative;top:50%;width:38px;height:38px;" src="img/spin.svg" />
        </div>
        <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:980px;height:380px;overflow:hidden;">
            {% for product in qs %}
			<div>
                <img data-u="image" src="https://static.ajkerdeal.com/img/banner/hometop/offer21118525852585258525852589.jpg" />
                <div u="thumb">Slide Description 001
                </div>
            </div>
			{% endfor %}
        </div><a data-scale="0" href="https://www.jssor.com" style="display:none;position:absolute;">image gallery</a>
        <!-- Thumbnail Navigator -->
        <div u="thumbnavigator" style="position:absolute;bottom:0px;left:0px;width:980px;height:50px;color:#FFF;overflow:hidden;cursor:default;background-color:rgba(0,0,0,.5);">
            <div u="slides">
                <div u="prototype" style="position:absolute;top:0;left:0;width:980px;height:50px;">
                    <div u="thumbnailtemplate" style="position:absolute;top:0;left:0;width:100%;height:100%;font-family:arial,helvetica,verdana;font-weight:normal;line-height:50px;font-size:16px;padding-left:10px;box-sizing:border-box;"></div>
                </div>
            </div>
        </div>
        <!-- Arrow Navigator -->
        <div data-u="arrowleft" class="jssora061" style="width:55px;height:55px;top:0px;left:25px;" data-autocenter="2" data-scale="0.75" data-scale-left="0.75">
            <svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                <path class="a" d="M11949,1919L5964.9,7771.7c-127.9,125.5-127.9,329.1,0,454.9L11949,14079"></path>
            </svg>
        </div>
        <div data-u="arrowright" class="jssora061" style="width:55px;height:55px;top:0px;right:25px;" data-autocenter="2" data-scale="0.75" data-scale-right="0.75">
            <svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                <path class="a" d="M5869,1919l5984.1,5852.7c127.9,125.5,127.9,329.1,0,454.9L5869,14079"></path>
            </svg>
        </div>
    </div>


<div class="spacer"></div>

<!-- header -->
<div class="ui container pad-top-30 pad-bottom-30">
	<div class="center aligned segment">
		<div class="ui horizontal divider">Monthly Specials</div>
	</div>
</div>

<div class="spacer"></div>

<!-- cards -->

<div class="ui container">

	<div class="ui four column grid">

		<div class="row">
			{% for product in qs %}

			<div class="column">
				<div class="ui card">
					<div class="image">
						<a class="ui red right ribbon label">-50%</a>
						<img  src="{{product.image1.url}}" />
					</div>
					<div class="content">
						<a class="header" href="{% url 'product:details' product.product_id %}">{{product.product_name}}</a>
						<div class="description">
							{{product.product_description}}
						</div>
					</div>
					<div class="extra content">
						<a class="ui teal tag label">{{product.price}}</a>

					</div>
				</div>
			</div>
			<div class="spacer"></div>
			{% endfor %}
		</div>

	</div>
</div>



{% endblock content %}
{% block scripts %}
<!--<script>-->
<!--var myIndex = 0;-->
<!--carousel();-->

<!--function carousel() {-->
<!--  var i;-->
<!--  var x = document.getElementsByClassName("mySlides");-->
<!--  for (i = 0; i < x.length; i++) {-->
<!--    x[i].style.display = "none";-->
<!--  }-->
<!--  myIndex++;-->
<!--  if (myIndex > x.length) {myIndex = 1}-->
<!--  x[myIndex-1].style.display = "block";-->
<!--  setTimeout(carousel, 2000); // Change image every 2 seconds-->
<!--}-->
<!--</script>-->
<script type="text/javascript">jssor_1_slider_init();
    </script>
{% endblock scripts %}